/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Cart {
  createdAt: Generated<string>;
  id: Generated<number | null>;
  username: string;
}

export interface CartItem {
  createdAt: Generated<string>;
  id: Generated<number | null>;
  name: string;
}

export interface DB {
  cart: Cart;
  cartItem: CartItem;
}
